import type { Metadata } from "next";
import { fontGeistMono, fontGeistSans, fontInter } from "@/lib/constant/font";
import { cn } from "@/lib/utils";
import Providers from "@/src/providers";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className={cn(
				"h-full",
				"antialiased",
				fontGeistSans.variable,
				fontGeistMono.variable,
				"font-sans",
				fontInter.variable,
			)}>
			<body className='flex min-h-full flex-col'>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
